var annotated =
[
    [ "builder_form", "classbuilder__form.html", "classbuilder__form" ],
    [ "color_input", "classcolor__input.html", "classcolor__input" ],
    [ "crud", "interfacecrud.html", "interfacecrud" ],
    [ "crud_form", "classcrud__form.html", "classcrud__form" ],
    [ "database_form", "classdatabase__form.html", "classdatabase__form" ],
    [ "datalist_input", "classdatalist__input.html", "classdatalist__input" ],
    [ "date_input", "classdate__input.html", "classdate__input" ],
    [ "db_form", "classdb__form.html", "classdb__form" ],
    [ "email_form_values", "classemail__form__values.html", "classemail__form__values" ],
    [ "email_input", "classemail__input.html", "classemail__input" ],
    [ "event", "classevent.html", "classevent" ],
    [ "field", "interfacefield.html", "interfacefield" ],
    [ "file_form", "classfile__form.html", "classfile__form" ],
    [ "forms", "classforms.html", "classforms" ],
    [ "get_input", "classget__input.html", "classget__input" ],
    [ "hidden_input", "classhidden__input.html", "classhidden__input" ],
    [ "input", "classinput.html", "classinput" ],
    [ "input_group", "classinput__group.html", "classinput__group" ],
    [ "matrix_input", "classmatrix__input.html", "classmatrix__input" ],
    [ "message", "classmessage.html", "classmessage" ],
    [ "number_input", "classnumber__input.html", "classnumber__input" ],
    [ "observable", "interfaceobservable.html", "interfaceobservable" ],
    [ "observer", "classobserver.html", "classobserver" ],
    [ "password_input", "classpassword__input.html", "classpassword__input" ],
    [ "private_get_input", "classprivate__get__input.html", null ],
    [ "range_input", "classrange__input.html", "classrange__input" ],
    [ "tel_input", "classtel__input.html", "classtel__input" ],
    [ "text_input", "classtext__input.html", "classtext__input" ],
    [ "textarea", "classtextarea.html", "classtextarea" ],
    [ "texteditor", "classtexteditor.html", "classtexteditor" ],
    [ "time_input", "classtime__input.html", "classtime__input" ],
    [ "zip_input", "classzip__input.html", "classzip__input" ]
];